version: '3.9'
services:
  jupyter-notebook:
    build: .
    ports:
      - '8080:8080'
    environment:
      - PYTHONHASHSEED=0
    volumes:
      - .:/mnt/notebook
    networks:
      - nmm-net

networks:
  nmm-net:
    name: nmm-network
